# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - tesseract=5.3.0               # https://github.com/tesseract-ocr/tesseract
  - pip:
    - rpaframework==28.4.1        # https://rpaframework.org/releasenotes.html
    - rpaframework-recognition==5.2.3
    - robocorp==2.0.0
